#!/usr/bin/env python
import numpy as np
filer = open("sample.txt", "r")
filew = open("converted.pcd", "w")
numlines = len(filer.readlines())
filew.write("# .PCD v.7 - Point Cloud Data file format\n")
filew.write("VERSION .7\n")
filew.write("FIELDS x y z\n")
filew.write("SIZE 4 4 4\n")
filew.write("TYPE F F F\n")
filew.write("COUNT 1 1 1\n")
filew.write("WIDTH %d\n" %numlines)
filew.write("HEIGHT 1\n")
filew.write("VIEWPOINT 0 0 0 1 0 0 0\n")
filew.write("POINTS %d\n" %numlines)
filew.write("DATA ascii\n")
def spherical2cartesian(r, theta, phi):
    x = r * np.sin(theta*np.pi/180) * np.cos(phi*np.pi/180)
    z = -1 * r * np.sin(theta*np.pi/180) * np.sin(phi*np.pi/180)
    y = -1 * r * np.cos(theta*np.pi/180)
    filew.write("%f %f %f\n" %(x,y,z))
filer = open("sample.txt", "r")
for line in filer:
    v, h, e, d = line.split(" ")
    v = float(v.replace("V",""))
    h = float(h.replace("H",""))
    d = float(d.replace("\n",""))
    spherical2cartesian(d, v, h)
filer.close()
filew.close()